### ISSUE TITLE
how to get transaction_id use this lib

### ISSUE THREAD

**Issue by hiquanta** [xeroc/python-bitshares#35]

**Comment by xeroc** [comment]
Currently, there is no way to obtain the transaction_id from the library nor from the witness API.
I'll need to talk to the backend devs to see how that can be implemented

**Comment by grctest** [comment]
https://btsapi.grcnode.co.uk/get_bts_oject?object_id=1.11.131039395&api_key=123abc

You can get the tx object directly, its output in account history, not available within the market history (but it would make sense to be included..)

**Comment by xeroc** [comment]
This may help you:
https://steemit.com/bitshares/@xeroc/python-bitshares-how-to-derive-transaction-ids
As a remark:
Id derivation may fail for transactions that have a `limit_order_creation_operation` in them since the bitshares-core reports dates wrongly sometimes .. https://github.com/bitshares/bitshares-core/issues/597
