### ISSUE TITLE
Still reading storage config url when I specified the node url

### ISSUE THREAD

**Issue by squarezhou** [xeroc/python-bitshares#36]
I found some bugs in the code when I was using it. 

Such as the Asset Class, you did not pass the bitshares_instance variable to the parent class.

I think this bug is also exist in other Class file, please check and fix it, thanks.

bitshares/asset.py line 43
`super().__init__(
            asset,
            lazy=lazy,
            full=full,
            bitshares_instance=None
        )`

bitshares/asset.py line 52
`super(Asset, self).__init__(asset)`

**Comment by xeroc** [comment]
Thanks for the bug report. In fact, I found quite a few that needed fixing.
The only issue i couldn't fix yet is the use of Account() in wallet.py which has no access to self.bitshares because it is instanciated during __init__ of BitShares(). Need to do some testing and see if that works as desired.
